export { CONTACT_EMAIL, CONTACT_GITHUB, CONTACT_LINKEDIN } from "./contact";
export {
  SITE_AUTHOR,
  SITE_DESCRIPTION,
  SITE_KEYWORDS,
  SITE_LOCALE,
  SITE_NAME,
  SITE_TITLE,
  SITE_URL,
} from "./seo";
