import {
  SiAnthropic,
  SiCss,
  SiCypress,
  SiDocker,
  SiExpress,
  SiFigma,
  SiGit,
  SiHibernate,
  SiHtml5,
  SiJavascript,
  SiJest,
  SiMongodb,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiNx,
  SiPostgresql,
  SiReact,
  SiReactquery,
  SiRedux,
  SiSpringboot,
  SiStorybook,
  SiTailwindcss,
  SiTypescript,
} from "react-icons/si";
import { TbApi, TbBrandRedux, TbDeviceMobile } from "react-icons/tb";

export const SKILLS_DATA = {
  frontend: {
    color: "red" as const,
    skills: [
      { name: "JavaScript", icon: SiJavascript },
      { name: "TypeScript", icon: SiTypescript },
      { name: "React", icon: SiReact },
      { name: "Next.js", icon: SiNextdotjs },
      { name: "HTML", icon: SiHtml5 },
      { name: "CSS", icon: SiCss },
      { name: "Redux", icon: SiRedux },
      { name: "Zustand", icon: TbBrandRedux },
      { name: "Tanstack Query", icon: SiReactquery },
      { name: "Tailwind CSS", icon: SiTailwindcss },
      { name: "Storybook", icon: SiStorybook },
      { name: "Cypress", icon: SiCypress },
      { name: "Jest", icon: SiJest },
    ],
  },
  backend: {
    color: "orange" as const,
    skills: [
      { name: "Java Spring Boot", icon: SiSpringboot },
      { name: "Spring Hibernate", icon: SiHibernate },
      { name: "Node.js", icon: SiNodedotjs },
      { name: "Nest.js", icon: SiNestjs },
      { name: "express.js", icon: SiExpress },
      { name: "PostgreSQL", icon: SiPostgresql },
      { name: "Mongo DB", icon: SiMongodb },
    ],
  },
  other: {
    color: "purple" as const,
    skills: [
      { name: "Claude Code", icon: SiAnthropic },
      { name: "Nx", icon: SiNx },
      { name: "Docker", icon: SiDocker },
      { name: "REST", icon: TbApi },
      { name: "RWD", icon: TbDeviceMobile },
      { name: "Git", icon: SiGit },
      { name: "Figma", icon: SiFigma },
    ],
  },
};
